### ISSUE TITLE
error by sending too large map through firos

### ISSUE THREAD

**Issue by marija185** [iml130/firos#2]
When trying to send map topic the following error message appears:
<class 'include.ros.topicHandler.nav_msgs.msg.OccupancyGrid'>
errorHTTP Error 413: Request Entity Too Large
HTTP Error 413: Request Entity Too Large
The map is from map_server ros package of pgm file. Three sizes were tested and with the size 166x182 pixels sending was successful. Size 332x363 pixels has the error result pasted above.

**Comment by ptrdtznr** [comment]
Hello @marija185 - could you maybe attach an file? It seems to me that Orion can't handle this file-size. Usually, by default, it has 1MB for a file. A 332x363 pixel mab has actually 120516 Pixel (=964128 Bytes). If there are some additional information, we are above the limit...

**Comment by marija185** [comment]
Here are two tested maps - one OK and one too big. The unsucc one is 120kB and succ one is 30kb.
[bitmaps.zip](https://github.com/iml130/firos/files/2672741/bitmaps.zip)

**Comment by ptrdtznr** [comment]
ah so maybe the "envelope" of "type/value" creates the overhead... We will look into it..

**Comment by ptrdtznr** [comment]
This is actually, as I thought, a limitation of Orion: 
[Orion Known Limitations](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/known_limitations.md)

**Comment by marija185** [comment]
Thanks @ptrdtznr! Then this issue can be closed.

**Comment by ptrdtznr** [comment]
Checked the code here [Orion Limits](https://github.com/telefonicaid/fiware-orion/blob/8f2e12356aa023c6e55ee58bcc101c334bd5c8ef/src/lib/common/limits.h)

```
/* ****************************************************************************
*
* PAYLOAD_MAX_SIZE - 
*/
#define PAYLOAD_MAX_SIZE (1 * 1024 * 1024) // 1 MB Maximum size of the payload
```

But thanks for testing, we will think about a solution...

**Comment by iml-dlux** [comment]
I have changed a lot in e4093cee4cec9493409149eb98ed83d4c9d98654 . Mainly the Communication between the Context-Broker and firos is updated to NGSI v2. But also the Object-Converter is now used differently, which results in a much lower overhead.  (for linking)

**Comment by Luxxii** [comment]
FIROS uses a newser Version of the ObjectConverter. The new version converts long Byte-Data (like `int[]` or `uint[]` as in `nav_msgs/OccupancyGrid.msg`) into Base64. Also there are some more new Options available for FIROS. The limit we currently have in the Orion Context-Broker (`PAYLOAD_MAX_SIZE = 2^20` ) is the only limit preventing us from pushing Images and other larger ROS-Messages onto it.

This limit can be manually changed inside the Docker of the Context-Broker itself. Orion will also have it configurable ([see here](https://github.com/telefonicaid/fiware-orion/issues/3492)).

Since this Issue cannot be solved by us, i'll close it down.

Greetings!
